### ISSUE TITLE
Comments on your project.

### ISSUE THREAD

**Issue by joseph-hellerstein** [klatimer/robot-data-visualizer#3]
Great to see that you have tests for your code. That said, it doesn't seem that you have much code right now. So, be careful that you are progressing fast enough to have a complete project by end of quarter. Also, your design documents must be readable from github. You can either move them to markdown or create PDF files from your docx files.

**Comment by klatimer** [comment]
Joe, thanks for the feedback. The docs were changed to PDF format and we have made significant progress over these last couple of weeks (GPS overlay on a map and basic visualization of lidar scans). Closing this for now.
